name: Python CI + SonarCloud

on:
  push:
    branches: [ main ]            # Build only when code is pushed to main
  pull_request:
    branches: [ "*" ]             # Build for PRs targeting ANY branch
  workflow_dispatch:              # Optional: allows manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for full SonarCloud analysis

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest coverage

      - name: Run tests and generate coverage
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest --maxfail=5 --disable-warnings --cov=. --cov-report xml:coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.organization=maddineniOrg
            -Dsonar.projectKey=rag-ai-agent
            -Dsonar.python.coverage.reportPaths=coverage.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
